###
POST http://localhost:8080/api/v1/articleLike/like/02896bdd-c89a-4512-b291-824a219f1578
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE1NzE2NjMsInBob25lIjoiKzk5ODk5MDAwMDAwMCIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE2OTE2NTgwNjQsImlzcyI6Imt1biB1eiB0ZXN0IHBvcnRhbGkifQ.SGlAG7KSo_FN-CaQsA1m7_bUJaJPCKNJakPwOPF4wI7UWsVS7aZEQxUSipeyPW37MeNIIVreWEueIl50tlHZAg


###
DELETE http://localhost:8080/api/v1/articleLike/remove/02896bdd-c89a-4512-b291-824a219f1578
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTE1NzE2NjMsInBob25lIjoiKzk5ODk5MDAwMDAwMCIsInJvbGUiOiJST0xFX1VTRVIiLCJleHAiOjE2OTE2NTgwNjQsImlzcyI6Imt1biB1eiB0ZXN0IHBvcnRhbGkifQ.SGlAG7KSo_FN-CaQsA1m7_bUJaJPCKNJakPwOPF4wI7UWsVS7aZEQxUSipeyPW37MeNIIVreWEueIl50tlHZAg