
 ### Create
POST http://localhost:8080/api/v1/profile
Content-Type: application/json


{
  "name": "Eshmat",
  "surname": "Eshmatov",
  "email": "eshmat@gmaol.com",
  "phone": "+998901234561",
  "password": "eshmat123",
  "role": "PUBLISHER"

}

### Update
PUT http://localhost:8080/api/v1/profile/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NTcxNTIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjQzNTIsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.RN4Pm4kli0pPJU_QZcn8oFUQdseD8Vj4wWgkKn-z_uzJsP8LJaYPQaWq0s1EjTgMG-d17XsPD-tCUvEMluX0iQ

{
  "name": "Alijon"

}

### Update detail
PUT http://localhost:8080/api/v1/profile/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NTcxNTIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjQzNTIsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.RN4Pm4kli0pPJU_QZcn8oFUQdseD8Vj4wWgkKn-z_uzJsP8LJaYPQaWq0s1EjTgMG-d17XsPD-tCUvEMluX0iQ

{
  "name": "MENMANMEN",
  "surname": "SEN"
}


### Get all
GET http://localhost:8080/api/v1/profile/all?page=1&size=4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NTcxNTIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjQzNTIsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.RN4Pm4kli0pPJU_QZcn8oFUQdseD8Vj4wWgkKn-z_uzJsP8LJaYPQaWq0s1EjTgMG-d17XsPD-tCUvEMluX0iQ


### Delete
DELETE http://localhost:8080/api/v1/profile/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NTcxNTIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjQzNTIsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.RN4Pm4kli0pPJU_QZcn8oFUQdseD8Vj4wWgkKn-z_uzJsP8LJaYPQaWq0s1EjTgMG-d17XsPD-tCUvEMluX0iQ


### Filter
GET http://localhost:8080/api/v1/profile/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk3NTcxNTIsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk3NjQzNTIsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.RN4Pm4kli0pPJU_QZcn8oFUQdseD8Vj4wWgkKn-z_uzJsP8LJaYPQaWq0s1EjTgMG-d17XsPD-tCUvEMluX0iQ

{
  "name": "Eshmat"
}